POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "testing",
  "email": "exp@email.com",
  "password": "012345678",
  "role": "operator"
}


POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "testing",
  "password": "012345678"
}
