# Generated by Django 5.2.8 on 2025-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mmsi', models.CharField(max_length=20, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(help_text='Speed in knots')),
                ('heading', models.FloatField(help_text='Direction in degrees')),
                ('status', models.CharField(choices=[('at_sea', 'At Sea'), ('at_port', 'At Port')], default='at_sea', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
