# Generated by Django 5.2.8 on 2025-12-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('fishing', 'Fishing'), ('patrol', 'Patrol'), ('tanker', 'Tanker')], default='cargo', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(help_text='Direction in degrees (0–360)'),
        ),
    ]
