# Generated by Django 5.2.8 on 2026-01-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vessel_vessel_type_alter_vessel_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('docking_capacity', models.PositiveIntegerField(help_text='Maximum number of vessels that can dock')),
            ],
        ),
        migrations.AlterField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0–360)', null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='current_port',
            field=models.ForeignKey(blank=True, help_text='Port where the vessel is currently docked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docked_vessels', to='api.port'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='destination_port',
            field=models.ForeignKey(blank=True, help_text='Final destination port of the vessel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_vessels', to='api.port'),
        ),
        migrations.CreateModel(
            name='PortVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_visits', to='api.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='api.vessel')),
            ],
            options={
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
