# Generated by Django 6.0.1 on 2026-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_port_alter_vessel_heading_vessel_current_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
