# Generated by Django 6.0.1 on 2026-01-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_port_latitude_port_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='api.vessel')),
            ],
            options={
                'indexes': [models.Index(fields=['vessel', 'recorded_at'], name='api_vesselp_vessel__ae1fa6_idx')],
            },
        ),
    ]
