# Generated by Django 6.0.1 on 2026-01-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_type',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('admin_approve', 'Admin Approved'), ('admin_reject', 'Admin Rejected'), ('role_change', 'Role Changed'), ('user_toggle', 'User Activated/Deactivated'), ('broadcast', 'Broadcast Sent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
