# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_auditlog_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselalert',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.vessel'),
        ),
    ]
